### ISSUE TITLE
django-storages compatibility

### ISSUE THREAD

**Issue by denisvlr** [aamirbhat/django-create-react-app#14]
In production it's common to use `django-storages`, when running `collectstatic` the files are sent to a CDN (for example AWS buckets). 

With this setup, `{% static "js/myscript.js %}` is then replaced by `https://mybucket.aws.com/static/js/myscript.js` in templates.

Here it's not working, the `render_bundle_js` points to local files (starting with `/static`)

(Great package by the way!)

**Comment by aamirbhat** [comment]
This feature is supported in 0.9.0
